import { createApp } from 'vue';
import { createPinia } from 'pinia';
import router from './route';
import 'qyani-components/dist/style.css';
import './private.css';
import App from './App.vue';
const app = createApp(App);
app.use(createPinia());
app.use(router);
app.mount('#app');
