import { createApp } from 'vue';
import App from './App.vue';
import 'qyani-components/dist/style.css';
import './private.css';
import { createPinia } from 'pinia';
import { router } from './route';
const pinia = createPinia();
const app = createApp(App);
app.use(pinia);
app.use(router);
app.mount('#app');
